<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..\..\..\..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsQuery.NETStandard" Version="1.3.6.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\bam.base\bam.base\bam.base.csproj" />
    <ProjectReference Include="..\..\bam.console\bam.console\bam.console.csproj" />
    <ProjectReference Include="..\..\bam.data.repositories\bam.data.repositories\bam.data.repositories.csproj" />
    <ProjectReference Include="..\..\bam.data.schema\bam.data.schema\bam.data.schema.csproj" />
    <ProjectReference Include="..\..\bam.data\bam.data\bam.data.csproj" />
    <ProjectReference Include="..\bam.activity\bam.activity.csproj" />
  </ItemGroup>

</Project>
